import { getBoardConfig } from '../boards/registry';

export class ArduinoCompiler {
  private includes: Map<string, string> = new Map();
  private globals: Map<string, string> = new Map();
  private setups: Map<string, string> = new Map();
  private loops: Map<string, string> = new Map();
  private isAVR: boolean = false;
  public boardId: string = '';
  private memoryUsed: number = 0;
  private _serialConfigured: boolean = false;

  public init(boardId: string) {
    this.includes.clear();
    this.globals.clear();
    this.setups.clear();
    this.loops.clear();
    this.memoryUsed = 0;
    this._serialConfigured = false;
    this.boardId = boardId;
    
    const board = getBoardConfig(boardId);
    this.isAVR = !!board.isAVR;
  }

  public addInclude(includeStr: string, key?: string) {
    const k = key || includeStr;
    if (!this.includes.has(k)) {
      this.includes.set(k, includeStr);
    }
  }

  public addGlobal(globalStr: string, key?: string) {
    const k = key || globalStr;
    if (!this.globals.has(k)) {
      this.globals.set(k, globalStr);
    }
  }

  public addSetup(setupStr: string, key?: string) {
    const k = key || setupStr;
    if (!this.setups.has(k)) {
      this.setups.set(k, setupStr);
    }
  }

  public addLoop(loopStr: string, key?: string) {
    const k = key || loopStr;
    if (!this.loops.has(k)) {
      this.loops.set(k, loopStr);
    }
  }

  public emitValue(value: string, type: 'int' | 'float' | 'string' | 'bool'): string {
    if (value === null || value === undefined) return '';
    if (type === 'float') {
      const parsed = parseFloat(value);
      return isNaN(parsed) ? value : `${parsed.toFixed(1)}f`;
    }
    if (type === 'int') {
      const parsed = parseInt(value, 10);
      return isNaN(parsed) ? value : `${parsed}`;
    }
    return value;
  }

  /** Signal that Serial has been configured by a block (suppresses default Serial.begin) */
  public setSerialConfigured() {
    this._serialConfigured = true;
  }

  public wrapString(str: string): string {
    if (this.isAVR) {
       this.memoryUsed += str.length + 1; // Approximate static RAM
       return `F("${str}")`;
    }
    return `"${str}"`;
  }

  public getMemoryWarning(): string | null {
    if (this.isAVR) {
        const board = getBoardConfig(this.boardId);
        // Warning if static strings take more than 50% of RAM (just an estimation for UI)
        if (this.memoryUsed > (board.ram * 1024 * 0.5)) {
             return `Warning: Estimated memory usage is high (${this.memoryUsed} bytes used for static strings). Arduino Uno/Nano may become unstable.`;
        }
    }
    return null;
  }

  public assemble(mainCode: string): string {
    const board = getBoardConfig(this.boardId);
    
    // Core includes
    let finalCode = `// Generated by BitBlock — ${board.name}\n// Board: ${board.id}\n\n`;
    finalCode += `#include <Arduino.h>\n`;
    
    // Custom includes
    Array.from(this.includes.values()).forEach(inc => {
      finalCode += inc + "\n";
    });
    
    finalCode += "\n";
    
    // Globals
    Array.from(this.globals.values()).forEach(glb => {
      finalCode += glb + "\n";
    });
    
    finalCode += "\n";
    
    // Setup
    finalCode += "void setup() {\n";
    if (!this._serialConfigured && (board.id !== 'arduino-uno-r3' && board.id !== 'arduino-nano')) {
      finalCode += "  Serial.begin(115200);\n";
      finalCode += "  delay(100);\n";
    } else if (!this._serialConfigured && (board.id === 'arduino-uno-r3' || board.id === 'arduino-nano')) {
      finalCode += "  Serial.begin(9600);\n";
    }
    
    Array.from(this.setups.values()).forEach(setup => {
      finalCode += "  " + setup.replace(/\n/g, "\n  ") + "\n";
    });
    
    finalCode += "}\n\n";
    
    // Loop
    finalCode += "void loop() {\n";
    finalCode += "  " + mainCode.replace(/\n/g, "\n  ") + "\n";
    
    Array.from(this.loops.values()).forEach(l => {
      finalCode += "  " + l.replace(/\n/g, "\n  ") + "\n";
    });
    
    finalCode += "}\n";
    return this.formatCode(finalCode);
  }

  private formatCode(code: string): string {
    // ── Pass 1: Indentation ──────────────────────────────────────────────
    const INDENT = "  ";
    const lines = code.split("\n");
    let depth = 0;
    const formatted: string[] = [];

    for (const rawLine of lines) {
      const trimmed = rawLine.trim();

      if (!trimmed) {
        formatted.push("");
        continue;
      }

      // Keep preprocessor lines at column 0.
      if (trimmed.startsWith("#")) {
        formatted.push(trimmed);
        continue;
      }

      // Keep single-line comments at column 0 only when at top level
      if (trimmed.startsWith("//") && depth === 0) {
        formatted.push(trimmed);
        continue;
      }

      // Dedent lines that start with a closing brace just for printing
      let printDepth = depth;
      if (trimmed.startsWith("}")) {
        printDepth = Math.max(0, depth - 1);
      }

      formatted.push(`${INDENT.repeat(printDepth)}${trimmed}`);

      // Update the running depth for the next line
      const openCount = (trimmed.match(/\{/g) || []).length;
      const closeCount = (trimmed.match(/\}/g) || []).length;
      depth = Math.max(0, depth + openCount - closeCount);
    }

    // ── Pass 2: Structural blank lines ───────────────────────────────────
    let result = formatted.join("\n");

    // One blank line after the last #include before non-#include content
    result = result.replace(/(#include [^\n]+)\n([^#\n])/g, '$1\n\n$2');

    // One blank line between closing brace and a new top-level function/type
    result = result.replace(/\}\n(void |int |float |bool |char |String |unsigned |long |double |struct |class |enum )/g, '}\n\n$1');

    // Collapse 3+ consecutive blank lines down to one blank line
    result = result.replace(/\n{3,}/g, '\n\n');

    // Remove trailing whitespace on each line
    result = result.split('\n').map(l => l.trimEnd()).join('\n');

    return result;
  }
}

export const compiler = new ArduinoCompiler();
