import { getBoardConfig } from '../boards/registry';

export class ArduinoCompiler {
  private includes: Set<string> = new Set();
  private globals: Set<string> = new Set();
  private setups: Set<string> = new Set();
  private loops: Set<string> = new Set();
  private isAVR: boolean = false;
  private boardId: string = '';
  private memoryUsed: number = 0;

  public init(boardId: string) {
    this.includes.clear();
    this.globals.clear();
    this.setups.clear();
    this.loops.clear();
    this.memoryUsed = 0;
    this.boardId = boardId;
    
    const board = getBoardConfig(boardId);
    this.isAVR = !!board.isAVR;
  }

  public addInclude(includeStr: string) {
    if (!this.includes.has(includeStr)) {
      this.includes.add(includeStr);
    }
  }

  public addGlobal(globalStr: string) {
    if (!this.globals.has(globalStr)) {
      this.globals.add(globalStr);
    }
  }

  public addSetup(setupStr: string) {
    if (!this.setups.has(setupStr)) {
      this.setups.add(setupStr);
    }
  }

  public addLoop(loopStr: string) {
    if (!this.loops.has(loopStr)) {
      this.loops.add(loopStr);
    }
  }

  public wrapString(str: string): string {
    if (this.isAVR) {
       this.memoryUsed += str.length + 1; // Approximate static RAM
       return `F("${str}")`;
    }
    return `"${str}"`;
  }

  public getMemoryWarning(): string | null {
    if (this.isAVR) {
        const board = getBoardConfig(this.boardId);
        // Warning if static strings take more than 50% of RAM (just an estimation for UI)
        if (this.memoryUsed > (board.ram * 1024 * 0.5)) {
             return `Warning: Estimated memory usage is high (${this.memoryUsed} bytes used for static strings). Arduino Uno/Nano may become unstable.`;
        }
    }
    return null;
  }

  public assemble(mainCode: string): string {
    const board = getBoardConfig(this.boardId);
    
    // Core includes
    let finalCode = `// Generated by BitBlock — ${board.name}\n// Board: ${board.id}\n\n`;
    finalCode += `#include <Arduino.h>\n`;
    
    // Custom includes
    this.includes.forEach(inc => {
      finalCode += inc + "\n";
    });
    
    finalCode += "\n";
    
    // Globals
    this.globals.forEach(g => {
      finalCode += g + "\n";
    });
    
    finalCode += "\nvoid setup() {\n  Serial.begin(115200);\n";
    
    // Initializations
    this.setups.forEach(s => {
      finalCode += `  ${s}\n`;
    });
    
    if (mainCode) {
      finalCode += `\n  // User Blocks\n${mainCode.split('\n').map(l => l ? '  ' + l : '').join('\n')}\n`;
    }
    
    finalCode += "}\n\nvoid loop() {\n";
    
    // Loop background tasks
    this.loops.forEach(l => {
      finalCode += `  ${l}\n`;
    });
    
    finalCode += "}\n";
    return this.formatCode(finalCode);
  }

  private formatCode(code: string): string {
    const INDENT = "  ";
    const lines = code.split("\n");
    let depth = 0;
    const formatted: string[] = [];

    for (const rawLine of lines) {
      const trimmed = rawLine.trim();

      if (!trimmed) {
        formatted.push("");
        continue;
      }

      // Keep preprocessor lines at column 0.
      if (trimmed.startsWith("#")) {
        formatted.push(trimmed);
        continue;
      }

      // Dedent lines that start with a closing brace.
      if (trimmed.startsWith("}")) {
        depth = Math.max(0, depth - 1);
      }

      formatted.push(`${INDENT.repeat(depth)}${trimmed}`);

      // Increase indent for opening braces, excluding lines that also close in place.
      const openCount = (trimmed.match(/\{/g) || []).length;
      const closeCount = (trimmed.match(/\}/g) || []).length;
      const delta = openCount - closeCount;
      if (!trimmed.startsWith("}")) {
        depth = Math.max(0, depth + delta);
      } else if (delta > 0) {
        depth += delta;
      }
    }

    return formatted.join("\n");
  }
}

export const compiler = new ArduinoCompiler();
